### PR TITLE
Fixing compilation. Before, tsc (3.0.3) was ...

### PR DESCRIPTION
**Pull request by robsman**
... reporting an error due to a duplicate declaration of console from
both the dom and node libraries.

### CODE REVIEW

**Comment by DonMartin76** [comment]
Thank you for your pull request!

I cannot reproduce the compiler error, neither on the build server (Linux/Dockerized) nor locally (macOS 10.13.6). I tried `tsc` 2.9.2, 3.0.3 and 3.1.1 (which is the current one, and the one the build server uses).

Under which circumstances does this occur? OS, build process,...?

**Comment by DonMartin76** [comment]
And with which node version?

**Comment by robsman** [comment]
I'm really puzzled as I fail to recreate this with a clean checkout myself. I had an error repeatedly this Thursday, stating a conflicting declaration of console between the _dom_ and _node_ tsc libraries, using various combinations of
* Node 8.11.3 and 10.11.0
* tsc 2.9.2, 3.0.3 and 3.1

Nevertheless, retried with a fresh clone and can't get it recreated. I suspect some kind of _node-modules/_ corruption on my end.

Still, the implicit `URL` type in _kong.ts_ is resolved to typescript's _dom_ library, so maybe the explicit import is useful.

I will keep an eye over the course of next week, maybe it is best to put this PR on hold until then?
Apologies for your time spent on chasing a ghost.

**Comment by DonMartin76** [comment]
All good, there are sometimes things with npm/tsc/... which only occur on specific combinations of tools; if I can do something against it (without breaking the other combinations), I am grateful for these things.

Putting on hold for now nevertheless.

**Comment by DonMartin76** [comment]
OK, so this was apparently a bug in the @types/node package. I now ran into it as well. It occurred with 10.11.1, but is fixed in yesterdays 10.11.3 version. See here:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29230

Closing this. Thanks!

**Comment by robsman** [comment]
Thanks for reporting this back.

**Pull request closed without merging**
